name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MongoDB dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev

      - name: Install dependencies and run tests
        working-directory: payments
        run: |
          npm ci
          npm run test:ci
